default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: action_cable_development

test:
  <<: *default
  database: action_cable_test

production:
  <<: *default
  database: action_cable_production
